---
projectName: events-time
projectVersion: '1.0'
projectType: plugin
defaultConfig:
  properties:
    port: 5003
    nameForHuman: Get Events
    nameForModel: events
    descriptionForHuman: A plugin that gets events within a user specified time range.
pluginServers:
  - serverId: events
    mockedRequests:
      - path: /time
        method: get
        mockedResponse: time.json
      - path: /events
        method: get
        mockedResponse: events.json