openapi: 3.0.0
info:
  title: HTML Page API
  version: 1.0.0
servers:
  - url: http://localhost:${port}
paths:
  /homepage:
    get:
      operationId: getHomepage
      summary: Get the homepage
      responses:
        '200':
          description: An HTML page
          content:
            text/html:
              schema:
                type: string