---
projectName: display-table
projectVersion: '1.0'
projectType: plugin
defaultConfig:
  properties:
    port: 5003
    nameForHuman: Display stock table
    nameForModel: stocks
    descriptionForHuman: An API to retrieve stock info

pluginServers:
  - serverId: stocks
    mockedRequests:
      - path: /stocks
        method: get
        mockedResponse: stocks.json
