---
projectName: display-markdown
projectVersion: '1.0'
projectType: plugin
defaultConfig:
  properties:
    port: 5003
    nameForHuman: Display markdown
    nameForModel: markdown
    descriptionForHuman: An API to retrieve markdown content

pluginServers:
  - serverId: simple-markdown
    mockedRequests:
      - path: /markdown
        method: get
        mockedResponse: README.md
        contentType: text/markdown
